services:
  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./data:/bitnami/redis/data
